apiVersion: apps/v1
kind: Deployment
metadata:
  name: conteudo-service
  namespace: educaonline
  labels:
    app: conteudo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conteudo-service
  template:
    metadata:
      labels:
        app: conteudo-service
    spec:
      containers:
        - name: conteudo
          image: educaonline.conteudo.api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: MessageQueueConnection__MessageBus
              value: "amqp://guest:guest@rabbitmq:5672"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: conteudo-service
  namespace: educaonline
spec:
  selector:
    app: conteudo-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
