apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: educaonline
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=  # base64 encoded 'guest'
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=  # base64 encoded 'guest'

---

apiVersion: v1
kind: Secret
metadata:
  name: messagebus-secret
  namespace: educaonline
type: Opaque
data:
  MESSAGE_BUS_URL: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzI=  # base64 encoded 'amqp://guest:guest@rabbitmq:5672'

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: educaonline
type: Opaque
data:
  JWT_SECRET: NDc2YTdmMTItNjFkNC00ZWY5LTkyYzUtNzQyMGU2OWUwYzgz  # base64 encoded '476a7f12-61d4-4ef9-92c5-7420e69e0c83'